### ISSUE TITLE
List of snippet categories

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/wp-dev-recipes#22]
A functional approach.

1. fix core problems, see #21 
1. fix plugin problems by hooking
1. add custom HTML snippets, e.g. tracking or live chat
1. admin page/menu cleaning
1. disabling default WordPress core features: updates, feeds, emojis, [XML-RPC](https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-disable-xmlrpc/disable-xmlrpc.php), comments, embeds, DNS prefetching, generator meta ...
1. reverse proxy/CDN URL manipulation
1. administration: webserver settings, object cache handling, see https://github.com/szepeviktor/tiny-cache/blob/master/README.md#wordpress-performance - people won't use WP-CLI
1. role/capability things, e.g. enable navigation menu editing for Editors
1. authentication, session management
1. debugging and development
1. tiny shortcodes

Does it help?

**Comment by szepeviktor** [comment]
Any reaction guys?

**Comment by jaydrogers** [comment]
Sorry to leave you hanging @szepeviktor! WordPress is a little out of my league (I am a server dude and a bad designer 😆)

@danpastori will get back soon, but he's slammed with some client work this week.

He should hopefully have some time to review later this week. Thanks for your contributions 🙌

**Comment by danpastori** [comment]
Hi @szepeviktor ,

Thank you for the detailed list of snippet categories! I definitely want to make the categories explicit as possible. With the discrepancies (#21) on where things should actually go (plugin vs theme) I'll do my best to distinguish. 

Right now I have about 30 recipes to be added, all divided up with the following Categories:

* Core
* Theme Development
* Plugin Development
* Woocommerce
* 3rd Party Plugin Integrations (Yoast, Contact Form 7)

I also plan on having a category to explain development methods which should help distinguish where to put these recipes. 

Does that help?

Thanks for the ideas too!

**Comment by szepeviktor** [comment]
:) I think this project is not for core contributors.

Please categorize my list above by your 5 categories.
Thanks.

**Comment by danpastori** [comment]
We'd definitely welcome any contributions.

Maybe I mis-understood, but is the list above recipes that you have created? If that's the case I can categorize them. I understood it as you had an idea for categories.

**Comment by szepeviktor** [comment]
Yes, please categorize my categories. I am curious how you see them!

**Comment by szepeviktor** [comment]
> is the list above recipes that you have created?

No they are Categories.
I have 60+ "snippets".

**Comment by danpastori** [comment]
Ah awesome, I understand now! Looks like you have a ton of recipes as well! The list I mentioned above is a baseline for where we are getting started. Since you have more, we can obviously add more categories.

## Core
1. fix core problems
5. Disabling Default WordPress features

## Plugin Development
2. Fix plugin problems by hooking
4. Admin page/menu cleaning
8. Role capability things.
9. Authentication/Session management

## Theme Development
3. Add Custom HTML Snippets
11. Tiny Shortcodes

One thing I'd note with "Core" is that those could live in a plugin or theme depending on where your main focus is developing your WP install. Making a custom plugin would probably be the best approach for configuration.

I'd say 6 & 7 from your list could be in a "Hosting" category? And 10 could be in a "Development Tools" category? Let me know your thoughts!
