### ISSUE TITLE
Generate Sitemap

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/wp-dev-recipes#6]
# Problem
* wp-dev-recipes.serversideup.net is not able to be easily indexed by Google

# Solution
* Implement [nuxt/sitemap](https://content.nuxtjs.org/integrations#nuxtjssitemap)

**Comment by danpastori** [comment]
I have this completed. However it isn't automated which I really need to look into. The documentation showed you can automate the routes, but it didn't work with the default theme since we installed differently which I found bizarre. Right now I have the site map being created with all of the routes in the application, but am looking into solutions to generate it.

**Comment by jaydrogers** [comment]
Since it is something we need to look into, let's just leave it open. Automatically generating the sitemap will be huge.

**Comment by danpastori** [comment]
Hi Jay,

This has been pushed and I confirmed it is generating a dynamic site map: https://wp-dev-recipes.serversideup.net/sitemap.xml. Let me know how this works!

**Comment by jaydrogers** [comment]
Great work Dan! 👏
